FROM node:20-alpine

WORKDIR /app

# Устанавливаем зависимости для разработки
COPY package*.json ./
RUN npm install

# Копируем исходный код
COPY . .

# Создаем директорию для uploads
RUN mkdir -p uploads

EXPOSE 3000

# Hot-reload с tsx watch
CMD ["npx", "tsx", "watch", "src/index.ts"]